alarm_settings:
  hour: "10:30"

  turn_on_led: True
  led_settings:
    gpio_led: 21

  turn_some_water: True
  water_settings:
    gpio_servo: 12
    init_value: 249
    end_value: 50
    chance_time: 20

  play_songs: True
  song_settings:
    song_folder: "./wakeup_songs/"