alarm_settings:
  hour: "18:30"

  turn_on_led: True
  led_settings:
    gpio_led: 10

  turn_some_water: True
  water_settings:
    gpio_servo: 8
    init_value: 50
    end_value: 249
    chance_time: 10

  play_songs: True
  song_settings:
    song_folder: "./wakeup_songs/"